### ISSUE TITLE
cordova-plugin-xapkreader & gradle (Cordova 5.0.0) error

### ISSUE THREAD

**Issue by Shinji89** [agamemnus/cordova-plugin-xapkreader#18]
Hi, after updating my project to cordova 5.0.0 i get this error if i run "cordova build android":

_expansion:downloader_library:compileDebugJavaD:\Dropbox\Documenti\App\actmindfu
lly\plugins\com.flyingsoftgames.xapkreader\android-sdk\extras\google\play_apk_ex
pansion\downloader_library\src\com\google\android\vending\expansion\downloader\i
mpl\DownloaderService.java:26: error: package com.google.android.vending.licensi
ng does not exist
import com.google.android.vending.licensing.AESObfuscator;
                                           ^
D:\Dropbox\Documenti\App\xxxxx\plugins\com.flyingsoftgames.xapkreader\and
roid-sdk\extras\google\play_apk_expansion\downloader_library\src\com\google\andr
oid\vending\expansion\downloader\impl\DownloaderService.java:27: error: package
com.google.android.vending.licensing does not exist
import com.google.android.vending.licensing.APKExpansionPolicy;
                                           ^
D:\Dropbox\Documenti\App\xxxxx\plugins\com.flyingsoftgames.xapkreader\and
roid-sdk\extras\google\play_apk_expansion\downloader_library\src\com\google\andr
oid\vending\expansion\downloader\impl\DownloaderService.java:28: error: package
com.google.android.vending.licensing does not exist
import com.google.android.vending.licensing.LicenseChecker;
                                           ^
D:\Dropbox\Documenti\App\xxxxx\plugins\com.flyingsoftgames.xapkreader\and
roid-sdk\extras\google\play_apk_expansion\downloader_library\src\com\google\andr
oid\vending\expansion\downloader\impl\DownloaderService.java:29: error: package
com.google.android.vending.licensing does not exist
import com.google.android.vending.licensing.LicenseCheckerCallback;
                                           ^
D:\Dropbox\Documenti\App\xxxxx\plugins\com.flyingsoftgames.xapkreader\and
roid-sdk\extras\google\play_apk_expansion\downloader_library\src\com\google\andr
oid\vending\expansion\downloader\impl\DownloaderService.java:30: error: package
com.google.android.vending.licensing does not exist
import com.google.android.vending.licensing.Policy;
                                           ^
D:\Dropbox\Documenti\App\xxxxx\plugins\com.flyingsoftgames.xapkreader\and
roid-sdk\extras\google\play_apk_expansion\downloader_library\src\com\google\andr
oid\vending\expansion\downloader\impl\DownloaderService.java:756: error: cannot
find symbol
            final APKExpansionPolicy aep = new APKExpansionPolicy(mContext,
                  ^
  symbol:   class APKExpansionPolicy
  location: class DownloaderService.LVLRunnable
D:\Dropbox\Documenti\App\xxxxx\plugins\com.flyingsoftgames.xapkreader\and
roid-sdk\extras\google\play_apk_expansion\downloader_library\src\com\google\andr
oid\vending\expansion\downloader\impl\DownloaderService.java:756: error: cannot
find symbol
            final APKExpansionPolicy aep = new APKExpansionPolicy(mContext,
                                               ^
  symbol:   class APKExpansionPolicy
  location: class DownloaderService.LVLRunnable
D:\Dropbox\Documenti\App\xxxxx\plugins\com.flyingsoftgames.xapkreader\and
roid-sdk\extras\google\play_apk_expansion\downloader_library\src\com\google\andr
oid\vending\expansion\downloader\impl\DownloaderService.java:757: error: cannot
find symbol
                    new AESObfuscator(getSALT(), mContext.getPackageName(), devi
ceId));
                        ^
  symbol:   class AESObfuscator
  location: class DownloaderService.LVLRunnable
D:\Dropbox\Documenti\App\xxxxx\plugins\com.flyingsoftgames.xapkreader\and
roid-sdk\extras\google\play_apk_expansion\downloader_library\src\com\google\andr
oid\vending\expansion\downloader\impl\DownloaderService.java:765: error: cannot
find symbol
            final LicenseChecker checker = new LicenseChecker(mContext, aep,
                  ^
  symbol:   class LicenseChecker
  location: class DownloaderService.LVLRunnable
D:\Dropbox\Documenti\App\xxxxx\plugins\com.flyingsoftgames.xapkreader\and
roid-sdk\extras\google\play_apk_expansion\downloader_library\src\com\google\andr
oid\vending\expansion\downloader\impl\DownloaderService.java:765: error: cannot
find symbol
            final LicenseChecker checker = new LicenseChecker(mContext, aep,
                                               ^
  symbol:   class LicenseChecker
  location: class DownloaderService.LVLRunnable
D:\Dropbox\Documenti\App\xxxxx\plugins\com.flyingsoftgames.xapkreader\and
roid-sdk\extras\google\play_apk_expansion\downloader_library\src\com\google\andr
oid\vending\expansion\downloader\impl\DownloaderService.java:768: error: cannot
find symbol
            checker.checkAccess(new LicenseCheckerCallback() {
                                    ^
  symbol:   class LicenseCheckerCallback
  location: class DownloaderService.LVLRunnable
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
11 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':..:..:plugins:com.flyingsoftgames.xAPKreader:android
-sdk:extras:google:play_APK_expansion:downloader_library:compileDebugJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info
 or --debug option to get more log output.
BUILD FAILED

Total time: 2.87 secs

D:\Dropbox\Documenti\App\xxxxx\platforms\android\cordova\node_modules\q\q
.js:126
                    throw e;
                          ^
Error code 1 for command: cmd with args: /s /c "D:\Dropbox\Documenti\App\xxxxx
\platforms\android\gradlew cdvBuildDebug -b D:\Dropbox\Documenti\App\xxxxx
\platforms\android\build.gradle -Dorg.gradle.daemon=true"
ERROR building one of the platforms: Error: D:\Dropbox\Documenti\App\xxxxx
\platforms\android\cordova\build.bat: Command failed with exit code 8
You may not have the required environment or OS to build this project
Error: D:\Dropbox\Documenti\App\xxxxx\platforms\android\cordova\build.bat
: Command failed with exit code 8
    at ChildProcess.whenDone (C:\Users\Marco\AppData\Roaming\npm\node_modules\co
rdova\node_modules\cordova-lib\src\cordova\superspawn.js:131:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)

D:\Dropbox\Documenti\App\xxxxx>ant debug install -Dout.dir=ant-build -Dge
n.absolute.dir=ant-gen
Buildfile: build.xml does not exist!
Build failed

**Comment by agamemnus** [comment]
Check whether ``project.properties`` still contains:
``android.library.reference.2=../../plugins/com.flyingsoftgames.xapkreader/android-sdk/extras/google/play_apk_expansion/downloader_library``

**Comment by Shinji89** [comment]
yes, the config is still the same

**Comment by agamemnus** [comment]
Then it's not being read, or you deleted the files.

Or... going on a lark here, but try putting your project files in C:\.

**Comment by Shinji89** [comment]
doesn't work, i tried:

C:\> ionic start myproject
CD myproject
ionic platform add android
cordova plugin add https://github.com/agamemnus/cordova-plugin-xapkreader.git

EDIT: project.properties -> ADDING AT THE BOTTOM:
android.library.reference.2=../../plugins/com.flyingsoftgames.xAPKreader/android-sdk/extras/google/play_APK_expansion/downloader_library

EDIT: android.json -> ADDING xapk_expansion_authority and xapk_google_play_public_key

ionic build android

RESULT is the same of the first message in this topic.

**Comment by agamemnus** [comment]
I'm going to go make a sample project (Cordova only) and see if it works.

**Comment by agamemnus** [comment]
Hmm.... you aren't supposed to add anything to android.json. You have to edit it, not add.

I added a 12-step instruction file and a test obb file for you to do:
https://github.com/agamemnus/cordova-plugin-xapkreader/tree/gh-pages/test-project-instructions-and-sample-obb

**Comment by MajorBreakfast** [comment]
I'm getting the same error. cordova@5.0 with cordova-android@4.0 and android-22 on Mac OS X Yosemite via the terminal.
I followed the instructions from above and created the project from the ground up.

- You probably could rename the included `main.1.com.testproject.obb` to `main.1.com.myproject.obb` so that it fits the instructions
- The `project.properties` already include `android.library.reference.1=CordovaLib`, so it's `android.library.reference.2=...` then.

**Comment by agamemnus** [comment]
Thanks for the "bug" reports.

I will see if I can compile it in Cordova 5. Looks like not. Maybe another Cordova issue.

**Comment by MajorBreakfast** [comment]
Thanks in advance!

**Comment by jordiv3d** [comment]
I'm also having some problem, since you update some files I can not make it work anymore...
I'm on cordova 4.3 and just few days ago it did work ...
And it keeps getting an error trying to download assets

**Comment by agamemnus** [comment]
Thanks for the report jordiv3d, I'm working on that and should be fixed shortly.

**Comment by jordiv3d** [comment]
Thanks !! do you think I could still use the old version just by replaciong all the files ?

**Comment by agamemnus** [comment]
jordiv3d, I made a change to the code so that the plugin *will check with the download service right away*. That was done to fix the issue of not having the files and the download service not starting. But it seems that the download service tries to phone home, or at least try validate the license key, meaning that unsigned apps (I think) don't work anymore.

I just tested my jigsaw game and it seems to be working perfectly. It's signed with the release key in debug mode.

It seems the solution here is to skip the download service initialization if an app is unsigned. I am unsure yet how to check for this, but I am open to suggestions.

**Comment by agamemnus** [comment]
For now, you can modify this line
in-src/android/XAPKDownloaderActivity.java:

if (versionList[i] == 0) return false;

Change the "return false;" to "continue;".

Make sure the change is in both files -- in your plugins/ and in your
platforms/android/src directory.

**Comment by agamemnus** [comment]
I updated the code now to test whether the build is a debug or release build.

**Comment by agamemnus** [comment]
Guys, I don't know. I don't get the error in Cordova 5.0.0...

**Comment by agamemnus** [comment]
As a side note, all my fresh 5.0 builds are failing. They didn't debug the Cordova build with Windows.

**Comment by jordiv3d** [comment]
thanks ! I just managed to make it work again with your tip !!

**Comment by agamemnus** [comment]
Well, I fixed the issue, so you can just re-install. (taking care to remove duplicates in platforms/android/res/values/xapkreader.xml and plugins/android.json)

**Comment by MajorBreakfast** [comment]
I still can't build the project.

Without adding `android.library.reference.2=...`:
```
/Users/josef/myproject/platforms/android/AndroidManifest.xml:15:13 Error:
	Missing one of the key attributes 'action#name,category#name' on element intent-filter at AndroidManifest.xml:15:13
```
Can be fixed by removing https://github.com/agamemnus/cordova-plugin-xapkreader/blob/f557d869eb4c489a693673d58dcddfd12b2edbc9/plugin.xml#L59

After adding `android.library.reference.2=...`:
```
:..:..:plugins:com.flyingsoftgames.xapkreader:android-sdk:extras:google:play_apk_expansion:downloader_library:compileDebugJava
/Users/josef/myproject/plugins/com.flyingsoftgames.xapkreader/android-sdk/extras/google/play_apk_expansion/downloader_library/src/com/google/android/vending/expansion/downloader/impl/DownloaderService.java:26: error: package com.google.android.vending.licensing does not exist
import com.google.android.vending.licensing.AESObfuscator;
...
```
I've thought that the licensing stuff was a dependency of the downloader library. I really don't get why it doesn't find it the package from within it.

All of the above errors appear in a freshly created test project.

**Comment by agamemnus** [comment]
MajorBreakfast,  jordiv3d had a different issue. I don't have a fix for the main issue of the thread. Are you using Windows? Can you compile without my plugin?

**Comment by MajorBreakfast** [comment]
My guess is that it's because cordova 5.0 uses gradle and the libs use ant.

BTW there is `<framework src="path/to/play-apk-expansion" custom="true" />` which can take care of the library reference. I still haven't figured out how to solve this issue. The problem is that the expansion lib doesn't find the licensing lib. I also don't know how much of that ant stuff can simply be deleted. I'm not really familiar with android development. With cordova wrapping all this stuff it's a huge layered cake and I don't get how it all fits together.

Here's an idea: Why not stick everything into the plugin's src dir. I think there's no need for having all this sublibraries.

**Comment by agamemnus** [comment]
Ok, I will see how I can rework those with gradle.

My concerns with sticking the plugins into the src dir are:

1) Other plugins might use portions of these librries, so there needs to be a way to easily ferret them out.
2) Licensing. The wording might get tricky on that...

**Comment by MajorBreakfast** [comment]
> Do you know what Cordova version the minimum for that is

No I don't but I can find issues for cordova@3.4 that mention it on stackoverflow. Since users aren't forced to upgrade, it's safe to support just the newest version of cordova anyway (IMO :).

> Licensing
I see that all the source files have the license on the top and things like the `android.manifest` are too simple in nature.

**Comment by agamemnus** [comment]
Er.. I don't understand your logic. If users aren't forced to upgrade, shouldn't this mean it should support as low a version as possible? Anyway, I'll look into it and see. 3.4 would probably be okay.

Here's another issue with adding libraries in the src/ code: they do modify them on occasion.

**Comment by MajorBreakfast** [comment]
My logic is that if I had to choose between the new and the old, I'd prefer support for the newer version of cordova. ;)

I hope that you manage to add the libraries as frameworks. I tried, but I couldn't get it to work.

**Comment by agamemnus** [comment]
Well, backwards-compatibility is fairly important as a lot of Cordova libraries are made by independent developers with little-to-no financial backing... so they won't be often updated and may get broken in new Cordova versions.

**Comment by imaffett** [comment]
@agamemnus  - We have a similar plugin we had forked at Intel and ran into this problem.  The issue is you need to add a build-extras.gradle file for the download_library.

https://github.com/imaffett/APKexpansion/commit/6edb062cf349ae2d4a7b6dbe65c86edb459db472#diff-6efcbef79311005333f7958248b4feb0R1

You may want to update your config.xml and add the projects as frameworks, but there is currently a bug where the project path is prefixed to the folder (we have a patch for Cordova 5)

**Comment by agamemnus** [comment]
Thanks for the info, imaffett. The bug kind of looks like a real headache. Did you mention the issue in Apache's JIRA site for Cordova? (I don't see it)

**Comment by imaffett** [comment]
@agamemnus no.  We have a committer on our team who is supposed to take care of it.  I already wrote the patch, it just has to go through the process.

**Comment by naranjamecanica** [comment]
Thanks @imaffett, with those changes I was able to build again, I did a fast patch on: https://github.com/naranjamecanica/cordova-plugin-xapkreader/commit/1f5d825b85969bad7e8801e6a419915d6694456b

The only manual change was needed in build-extras.gradle in 

    /platforms/android/com.flyingsoftgames.xapkreader/PROJECTNAME-downloader_library
to also append the project name to the library

    com.flyingsoftgames.xapkreader:PROJECTNAME-library

**Comment by agamemnus** [comment]
Does anyone know if this change, without appending the project name, breaks Cordova 4? (And does it break Cordova 4 even if the project name is appended?)

**Comment by naranjamecanica** [comment]
I'm sorry I did not test it and since I started making cordova apps since version 5 I have no experience with it. Next week I can test it if you want, when I have more time on my hands. Thanks

**Comment by Shinji89** [comment]
@naranjamecanica 
I tried your fix but i get this error

* Where:
Script 'C:\project\plugins\com.flyingsoftgames.xapkr
eader\android-sdk\extras\google\play_apk_expansion\downloader_library\build-extr
as.gradle' line: 2

* What went wrong:
A problem occurred evaluating script.
> Project with path ':com.flyingsoftgames.xapkreader:library' could not be found
 in project ':..:..:plugins:com.flyingsoftgames.xapkreader:android-sdk:extras:go
ogle:play_apk_expansion:downloader_library'.

Do i have to remove from project.properties the string "android.library.reference.2=../../plugins/com.flyingsoftgames.xapkreader/android-sdk/extras/google/play_apk_expansion/downloader_library" ? 

This is my the build_extras.gradle file (C:\project\plugins\com.flyingsoftgames.xapkreader\android-sdk\extras\google\play_apk_expansion\downloader_library\build-extras.gradle):
dependencies {
    debugCompile project(path: ':com.flyingsoftgames.xapkreader:library',configuration: "debug")
    releaseCompile project(path: ':com.flyingsoftgames.xapkreader:library',configuration: "release")
}

**Comment by agamemnus** [comment]
It's not working because you didn't add your project name. (that's why I haven't patched it yet)

``/platforms/android/com.flyingsoftgames.xapkreader/PROJECTNAME-downloader_library``

**Comment by Shinji89** [comment]
Do i have to manually create the directory (/platforms/android/com.flyingsoftgames.xapkreader/PROJECTNAME-downloader_library) ?
Is Project name the one in project_root/config.xml between <name></name>, right?

Thank you :)

**Comment by agamemnus** [comment]
No, I think you just need to set the name in the text file (``build-extras.gradle``), but I could be wrong. And yes, I think it is the ``id`` in config.xml.

**Comment by Shinji89** [comment]
Still getting the same error, i tried using "id" and "name" from config.xml, even the name used to create the project (i.e. cordova start project_name). I also tried to create the directory /platforms/android/com.flyingsoftgames.xapkreader/PROJECTNAME-downloader_library. 

I keep getting the error:
* What went wrong:
A problem occurred evaluating script.
> Project with path ':com.flyingsoftgames.xapkreader:PROJECTNAME-downloader_li
brary' could not be found in project ':..:..:plugins:com.flyingsoftgames.xapkrea
der:android-sdk:extras:google:play_apk_expansion:downloader_library'.

**Comment by shuklaalok7** [comment]
@agamemnus, Thanks a lot for this plugin. I don't have any experience of building cordova plugins. How much time do you think it may take to release the support for Cordova 5.0.0?

**Comment by agamemnus** [comment]
I will have to wait for Intel's patch to get to Cordova. Then it will be
fast.

**Comment by Shinji89** [comment]
Meanwhile we wait for the patch, @naranjamecanica could you please share more detailed steps to get the plugin work with cordova 5.0? Thank you :)

**Comment by agamemnus** [comment]
Are you sure you have ``PROJECTNAME-downloader_library`` and not ``PROJECTNAME-downloader_li brary``???

**Comment by Shinji89** [comment]
yep, it's just a copy & paste error, in the origianl file it's correct:

dependencies {
    debugCompile project(path: ':com.flyingsoftgames.xapkreader:PROJECTNAME-downloader_library',configuration: "debug")
    releaseCompile project(path: ':com.flyingsoftgames.xapkreader:PROJECTNAME-downloader_library',configuration: "release")
}

**Comment by agamemnus** [comment]
By the way, just in case anyone is wondering and is using Crosswalk, the migrate method doesn't work in 5.0. The plugin method does, however!

**Comment by shuklaalok7** [comment]
I just somehow want to read expansion file using cordova 5.0.0. I don't know how to develop a cordova plugin. Can something/someone help me here?

**Comment by agamemnus** [comment]
OK, I will see if I can replicate the steps mentioned by maffett... I can try for Thursday night.

**Comment by Shinji89** [comment]
@agamemnus Thank you!

**Comment by agamemnus** [comment]
Still haven't gotten to this. Had a 4-hour headache due some nasty softball "cheering" (massive uncontrolled yelling) occurring on a nearby field.

It would help if someone donated a million dollars. I could then support this plugin 24/7. :-D

**Comment by MajorBreakfast** [comment]
The good news is that once it works it will work for a while. The switch to gradle was something big after all.

**Comment by mattrayner** [comment]
If there's anything I can do to help with this I'd love to!

**Comment by agamemnus** [comment]
I'm finally basically done with my work project so I will put in some time tomorrow (er, today) to try the Intel fix and see why some might not have the success @naranjamecanica was having on this.

**Comment by atukilham** [comment]
hi @agamemnus, i try your plugin with cordova cli 3, and it's working, great.
but i try cordova cli 5. i got errors with downloader_library.
i just uninstall and install again your plugin and follow instruction on readme file. 
i think i missed one step, but i try again. it's still error again with download library.
Can you help me?

**Comment by agamemnus** [comment]
Please post further comments in https://github.com/agamemnus/cordova-plugin-xapkreader/issues/22.

**Comment by 4blocksinc** [comment]
how to resolve this issue can any one explain please 

Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* Where:
Script 'D:\sea\platforms\android\com.flyingsoftgames.xapkreader\sea-downloader_l
ibrary\build-extras.gradle' line: 2

* What went wrong:
A problem occurred evaluating script.
> Project with path ':com.flyingsoftgames.xapkreader:sea-library' could not be f
ound in project ':com.flyingsoftgames.xapkreader:downloader_library'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

**Comment by agamemnus** [comment]
Potentially related to most-recent update.

When did you download the code?

**Comment by 4blocksinc** [comment]
few minutes earlier

**Comment by agamemnus** [comment]
Sorry I am kind of busy with something, but I should probably have updated the docs simultaneously. I don't have time to do that atm so I'll roll back the change. One moment.

**Comment by 4blocksinc** [comment]
ok, please cause we on the verge of completing the project and we are over due on the project so please help us

**Comment by agamemnus** [comment]
Ok, updated to older version.

**Comment by 4blocksinc** [comment]
so will the code be working now.

**Comment by agamemnus** [comment]
If you're using 5.3.1, yes.

**Comment by 4blocksinc** [comment]
is it possible for you to spare a few min so that you can clear the error please

**Comment by 4blocksinc** [comment]
is it possible for you to connect through teamviewer please

**Comment by agamemnus** [comment]
Sorry I'm very busy right now.

**Comment by 4blocksinc** [comment]
just a 10 min you can solve this

**Comment by agamemnus** [comment]
Make sure to uninstall first.

**Comment by agamemnus** [comment]
Also, please make sure to create a new Issue instead of posting to a random closed issue!

**Comment by 4blocksinc** [comment]
ok
